'use strict';
const W=540,H=960,SHEET_URL='runtime/people-atlas.png',FOOD_SHEET_URL='runtime/food-atlas.png',CHEF_SHEET_URL='runtime/chef-atlas.png';
const CHEF_FLOW=[{frame:0,label:'Sẵn sàng',ms:180},{frame:1,label:'Mở miệng',ms:180},{frame:2,label:'Ăn miếng 1',ms:190},{frame:3,label:'Nhai 1',ms:160},{frame:4,label:'Nhai 2',ms:160},{frame:5,label:'Nuốt',ms:190},{frame:6,label:'Thỏa mãn',ms:300},{frame:7,label:'Sẵn sàng',ms:180}];
const LIBRARY={Chicken:[['Đùi gà','people',22,120],['Cánh gà','people',23,110],['Gà cay','people',24,135]],Rice:[['Cơm trắng','people',37,95],['Cơm cà ri','people',38,115],['Cơm gia vị','people',42,105]],Burgers:[['Burger gà','people',26,125],['Gà cuộn','people',28,105]],Snacks:[['Khoai tây','people',33,85],['Hành vòng','people',34,90],['Samosa','people',35,100]],Drinks:[['Nước dừa','food','f5',35,true],['Sinh tố bơ','food','f6',35,true],['Kem bơ','food','f7',40,true]]};
const COMMENTS=['Măm măm, ngon quá!','Tuyệt vời, bác đầu bếp ơi!','Ngon bá cháy!','Thêm một miếng nữa đi!','Không thể rời mắt!'];
class Mukbang extends Phaser.Scene{
constructor(){super('mukbang');this.category='Chicken';this.progress=0;this.coin=0;this.busy=false;this.dragItem=null;}
preload(){this.load.spritesheet('people',SHEET_URL,{frameWidth:128,frameHeight:160});this.load.spritesheet('chef',CHEF_SHEET_URL,{frameWidth:240,frameHeight:220});this.load.image('food',FOOD_SHEET_URL);}
create(){this.category='Chicken';this.progress=0;this.coin=0;this.busy=false;this.dragItem=null;this.sliceFood();this.drawShell();this.drawLiveHeader();this.drawChef();this.drawTable();this.drawMenu();this.bindDrag();this.time.addEvent({delay:1700,loop:true,callback:()=>this.pushComment()});this.time.delayedCall(4200,()=>this.showGift());}
sliceFood(){const t=this.textures.get('food');for(let r=0;r<3;r++)for(let c=0;c<5;c++)t.add('f'+(r*5+c),0,c*240,r*220,240,220);}
drawShell(){const g=this.add.graphics();g.fillStyle(0x272727).fillRoundedRect(10,8,520,944,48);g.fillStyle(0x415064).fillRoundedRect(24,24,492,912,34);g.fillStyle(0xf0c18d).fillRect(31,207,478,523);g.fillStyle(0xb87649).fillRect(31,475,478,255);g.fillStyle(0xfff4d8).fillRoundedRect(31,730,478,196,20);this.add.rectangle(270,941,130,5,0x666666).setOrigin(.5);}
drawLiveHeader(){this.add.text(46,44,'LIVE',{fontFamily:'Arial Black',fontSize:'16px',color:'#fff',backgroundColor:'#e94f5b',padding:{x:9,y:6}});this.add.text(110,51,'MUKBANG',{fontFamily:'Arial Black',fontSize:'17px',color:'#fff'});this.viewer=this.add.text(385,51,'👁  1.2M',{fontStyle:'bold',fontSize:'13px',color:'#fff',backgroundColor:'#334152',padding:{x:8,y:6}});this.add.text(490,47,'×',{fontSize:'30px',color:'#fff'}).setOrigin(.5);this.commentGroup=this.add.container(48,91);for(let i=0;i<3;i++)this.makeComment(i,COMMENTS[i]);this.add.text(270,194,'KÉO MÓN ĂN VÀO MIỆNG BÁC',{fontFamily:'Arial Black',fontSize:'11px',color:'#ffe29a'}).setOrigin(.5);}
makeComment(row,text){const colors=[0x70b7e0,0x8fc46d,0xd483cc],y=row*38,b=this.add.rectangle(115,y,230,31,0x263342,.9).setOrigin(.5),a=this.add.circle(10,y,12,colors[row%3]),t=this.add.text(29,y,text,{fontSize:'12px',color:'#fff'}).setOrigin(0,.5);this.commentGroup.add([b,a,t]);}
pushComment(){if(this.progress>=600)return;const t=this.add.text(530,Phaser.Math.Between(100,190),Phaser.Utils.Array.GetRandom(COMMENTS),{fontSize:'12px',fontStyle:'bold',color:'#fff',backgroundColor:'#263342',padding:{x:10,y:7}}).setOrigin(0,.5).setDepth(20);this.tweens.add({targets:t,x:-250,duration:4700,onComplete:()=>t.destroy()});}
drawChef(){this.add.ellipse(270,450,265,34,0x4e2f25,.22);this.chef=this.add.sprite(270,350,'chef',0).setScale(1.42);this.tweens.add({targets:this.chef,y:344,duration:1100,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});this.statePill=this.add.text(270,459,'SẴN SÀNG',{fontFamily:'Arial Black',fontSize:'13px',color:'#fff',backgroundColor:'#c65e5e',padding:{x:14,y:6}}).setOrigin(.5);this.add.rectangle(270,494,410,18,0x3d3d3d).setStrokeStyle(2,0xffffff,.55);this.emotionFill=this.add.rectangle(66,488,4,12,0x72c96f).setOrigin(0);this.emotionText=this.add.text(270,520,'Hài lòng: 0%',{fontStyle:'bold',fontSize:'12px',color:'#fff4d4'}).setOrigin(.5);}
drawTable(){const foods=[LIBRARY.Chicken[0],LIBRARY.Chicken[2],LIBRARY.Burgers[0],LIBRARY.Snacks[0],LIBRARY.Rice[1],LIBRARY.Drinks[1]],pos=[[105,580],[270,575],[425,580],[105,675],[270,675],[425,675]];pos.forEach((p,i)=>{if(i<5)this.add.ellipse(p[0],p[1]+23,118,42,0xffeed8).setStrokeStyle(4,0x8e5137)});foods.forEach((food,i)=>this.foodSprite(food,pos[i][0],pos[i][1],food[1]==='food'?.38:(i<3?.62:.58),true));}
foodSprite(food,x,y,scale,drag){const s=this.add.sprite(x,y,food[1],food[2]).setScale(scale).setData('food',food);if(drag){s.setInteractive({useHandCursor:true});s.on('pointerdown',p=>this.beginDrag(food,p));this.tweens.add({targets:s,angle:{from:-1.5,to:1.5},duration:900+Phaser.Math.Between(0,250),yoyo:true,repeat:-1});}return s;}
drawMenu(){this.add.text(270,749,'THỰC ĐƠN CỦA BẠN',{fontFamily:'Arial Black',fontSize:'19px',color:'#623d32'}).setOrigin(.5);this.tabGroup=this.add.container();Object.keys(LIBRARY).forEach((name,i)=>{const x=76+i*97,b=this.add.text(x,781,name,{fontFamily:'Arial Black',fontSize:'11px',color:name===this.category?'#fff':'#66453b',backgroundColor:name===this.category?'#d86472':'#ead8b8',padding:{x:8,y:7}}).setOrigin(.5).setInteractive({useHandCursor:true});b.on('pointerup',()=>{this.category=name;this.drawMenuItems();this.drawTabsActive();});this.tabGroup.add(b);});this.menuItems=this.add.container();this.drawMenuItems();}
drawTabsActive(){this.tabGroup.list.forEach((b,i)=>{const on=Object.keys(LIBRARY)[i]===this.category;b.setBackgroundColor(on?'#d86472':'#ead8b8');b.setColor(on?'#fff':'#66453b');});}
drawMenuItems(){this.menuItems.removeAll(true);LIBRARY[this.category].forEach((food,i)=>this.addMenuCard(food,110+i*160,858));}
addMenuCard(food,x,y){const c=this.add.container(x,y),shadow=this.add.rectangle(0,5,130,105,0xbc9b78,.45),bg=this.add.rectangle(0,0,130,105,0xfff8e8).setStrokeStyle(3,0xe1bd91),s=this.add.sprite(0,-12,food[1],food[2]).setScale(food[1]==='food'?.25:.55),t=this.add.text(0,38,food[0],{fontFamily:'Arial Black',fontSize:'11px',color:'#66453b'}).setOrigin(.5);c.add([shadow,bg,s,t]).setSize(130,105).setInteractive({useHandCursor:true});c.on('pointerdown',p=>this.beginDrag(food,p));this.menuItems.add(c);}
bindDrag(){this.input.on('pointermove',p=>{if(this.dragItem)this.dragItem.setPosition(p.x,p.y)});this.input.on('pointerup',p=>{if(!this.dragItem)return;const item=this.dragItem,food=item.getData('food'),hit=Phaser.Math.Distance.Between(p.x,p.y,270,345)<125;this.dragItem=null;if(hit&&!this.busy){item.destroy();this.consume(food);}else this.tweens.add({targets:item,alpha:0,scale:0,duration:140,onComplete:()=>item.destroy()});});}
beginDrag(food,pointer){if(this.busy)return;this.dragItem?.destroy();this.dragItem=this.add.sprite(pointer.x,pointer.y,food[1],food[2]).setScale(food[1]==='food'?.28:.8).setDepth(50).setData('food',food);this.tweens.add({targets:this.dragItem,scaleX:'+=.08',scaleY:'+=.08',duration:120,yoyo:true});}
consume(food){this.busy=true;let step=0;const run=()=>{const state=CHEF_FLOW[step];this.chef.setFrame(state.frame);this.statePill.setText(state.label.toUpperCase());this.tweens.add({targets:this.chef,scaleX:step===2?1.5:1.42,scaleY:step===2?1.34:1.42,duration:state.ms/2,yoyo:true});step++;if(step<CHEF_FLOW.length)this.time.delayedCall(state.ms,run);else{this.busy=false;this.addProgress(food[3]);}};run();}
addProgress(gain){this.progress=Math.min(600,this.progress+gain);this.tweens.add({targets:this.emotionFill,displayWidth:404*this.progress/600,duration:260});this.emotionText.setText(`Hài lòng: ${Math.round(this.progress/6)}%`);this.pushComment();if(this.progress>=600)this.finish();}
showGift(){if(this.progress>=600)return;const g=this.add.container(420,248).setScale(.2).setAlpha(0).setDepth(30),bg=this.add.rectangle(0,0,150,78,0xffe5a5).setStrokeStyle(4,0xe16870),tx=this.add.text(0,-14,'🎁 GIFT +50',{fontFamily:'Arial Black',fontSize:'15px',color:'#8d3d46'}).setOrigin(.5),btn=this.add.text(0,18,'NHẬN',{fontFamily:'Arial Black',fontSize:'12px',color:'#fff',backgroundColor:'#d95e6a',padding:{x:13,y:5}}).setOrigin(.5).setInteractive({useHandCursor:true});g.add([bg,tx,btn]);this.tweens.add({targets:g,scale:1,alpha:1,duration:280,ease:'Back.easeOut'});btn.on('pointerup',()=>{this.coin+=50;g.destroy();this.time.delayedCall(4500,()=>this.showGift());});}
finish(){this.busy=true;this.chef.setFrame(6);const p=this.add.container(270,470).setDepth(100).setScale(.2),bg=this.add.rectangle(0,0,410,235,0xfff2cf).setStrokeStyle(7,0xdd6672),title=this.add.text(0,-72,'MUKBANG HOÀN THÀNH!',{fontFamily:'Arial Black',fontSize:'22px',color:'#8c3f46'}).setOrigin(.5),reward=this.add.text(0,-18,`🪙 +${100+this.coin} COIN`,{fontFamily:'Arial Black',fontSize:'27px',color:'#d58b28'}).setOrigin(.5),again=this.add.text(0,55,'CHƠI LẠI',{fontFamily:'Arial Black',fontSize:'17px',color:'#fff',backgroundColor:'#dc6470',padding:{x:22,y:10}}).setOrigin(.5).setInteractive({useHandCursor:true});p.add([bg,title,reward,again]);again.on('pointerup',()=>this.scene.restart());this.tweens.add({targets:p,scale:1,duration:350,ease:'Back.easeOut'});}
}
window.__mukbangGame=new Phaser.Game({type:Phaser.CANVAS,parent:'game',width:W,height:H,scene:Mukbang,render:{antialias:true,roundPixels:true},fps:{target:60,min:30},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});
